export const NEW_POST_REQUEST = "NEW_POST_REQUEST";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_FAIL = "NEW_POST_FAIL";

export const GET_OWN_POSTS_REQUEST = "GET_OWN_POSTS_REQUEST";
export const GET_OWN_POSTS_SUCCESS = "GET_OWN_POSTS_SUCCESS";
export const GET_OWN_POSTS_FAIL = "GET_OWN_POSTS_FAIL";

export const GET_NEWSFEED_REQUEST = "GET_NEWSFEED_REQUEST";
export const GET_NEWSFEED_SUCCESS = "GET_NEWSFEED_SUCCESS";
export const GET_NEWSFEED_FAIL = "GET_NEWSFEED_FAIL";

export const FAVORITE_POST_REQUEST = "FAVORITE_POST_REQUEST";
export const FAVORITE_POST_SUCCESS = "FAVORITE_POST_SUCCESS";
export const FAVORITE_POST_FAIL = "FAVORITE_POST_FAIL";

export const REACT_POST_REQUEST = "REACT_POST_REQUEST";
export const REACT_POST_SUCCESS = "REACT_POST_SUCCESS";
export const REACT_POST_FAIL = "REACT_POST_FAIL";

export const REACT_TYPE_LIKE = "REACT_TYPE_LIKE";
export const REACT_TYPE_COMMENT = "REACT_TYPE_COMMENT";