export const FAVORITE_POST_REQUEST = "FAVORITE_POST_REQUEST";
export const FAVORITE_POST_SUCCESS = "FAVORITE_POST_SUCCESS";
export const FAVORITE_POST_FAIL = "FAVORITE_POST_FAIL";

export const NEW_POST_REQUEST = "NEW_POST_REQUEST";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_FAIL = "NEW_POST_FAIL";

export const GET_OWN_POSTS_REQUEST = "GET_OWN_POSTS_REQUEST";
export const GET_OWN_POSTS_SUCCESS = "GET_OWN_POSTS_SUCCESS";
export const GET_OWN_POSTS_FAIL = "GET_OWN_POSTS_FAIL";