export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_UPDATE_ENABLE = "USER_UPDATE_ENABLE";
export const USER_UPDATE_DISABLE = "USER_UPDATE_DISABLE";
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_NOTFOLLOWING_REQUEST = "GET_NOTFOLLOWING_REQUEST";
export const GET_NOTFOLLOWING_SUCCESS = "GET_NOTFOLLOWING_SUCCESS";
export const GET_NOTFOLLOWING_FAIL = "GET_NOTFOLLOWING_FAIL";

export const GET_FOLLOWING_REQUEST = "GET_FOLLOWING_REQUEST";
export const GET_FOLLOWING_SUCCESS = "GET_FOLLOWING_SUCCESS";
export const GET_FOLLOWING_FAIL = "GET_FOLLOWING_FAIL";

export const PUT_FOLLOW_REQUEST = "PUT_FOLLOW_REQUEST";
export const PUT_FOLLOW_SUCCESS = "PUT_FOLLOW_SUCCESS";
export const PUT_FOLLOW_FAIL = "PUT_FOLLOW_FAIL";

export const PUT_UNFOLLOW_SUCCESS = "PUT_UNFOLLOW_SUCCESS";
export const PUT_UNFOLLOW_FAIL = "PUT_UNFOLLOW_FAIL";

export const CHECK_PROFILE_REQUEST = "CHECK_PROFILE_REQUEST";
export const CHECK_PROFILE_SUCCESS = "CHECK_PROFILE_SUCCESS";
export const CHECK_PROFILE_FAIL = "CHECK_PROFILE_FAIL";